devguide:
  greeting: "안녕하세요"

---

spring:
  profiles: stage
  
devguide:
  greeting: "스테이징 서버에 오신걸 환영합니다."

---

spring:
  profiles: dev
  
devguide:
  greeting: "개발 서버에 오신걸 환영합니다!"

---

spring:
  profiles: local
  
devguide:
  greeting: "홍캐리 로컬 서버에 오신걸 환영합니다."