devguide:
  greeting: "0000"

---

spring:
  profiles: stage
  
devguide:
  greeting: "1111"

---

spring:
  profiles: dev
  
devguide:
  greeting: "2222"

---

spring:
  profiles: local
  
devguide:
  greeting: "3333"
  