---
spring:
  profiles: local

db:
  server:
    ip:127.0.0.1

market:
  type:computer

---

spring:
  profiles:dev

db:
  server:
    ip:10.0.0.1

market:
  type:computer

---

spring:
  profiles:real

db:
  server:
    ip:10.0.0.100

market:
  type:computer