spring:
  profiles: local

db:
  server:
    ip:127.0.0.1
    user:localUser
    password:1234

market:
  type:computer

---

spring:
  profiles:dev

db:
  server:
    ip:10.0.0.1
    user:devUser
    password:1234

market:
  type:computer

---

spring:
  profiles:real

db:
  server:
    ip:10.0.0.100
    user:devUser
    password:1234

market:
  type:computer