db:
  server:
    ip: 127.0.0.1

market:
  type: computer
  
---
spring:
  profiles: local

db:
  server:
    ip: 128.0.0.111

user: localUser

---

spring:
  profiles: dev

db:
  server:
    ip: 18.0.0.122

user: devUser

---

spring:
  profiles: real

db:
  server:
    ip: 18.0.0.133

user: realUser